name: |-
  Main branch workflow
  
  Build, test Docker image, deploy it to EKS `dev` environment and draft new release  
  
  ### Usage 
  
  Create in your repo  __`.github/workflows/main.yaml`__
  
  ```yaml
    name: Main Branch
    on:
      push:
        branches: [ master ]
    
    permissions:
      contents: write
      id-token: write
    
    jobs:
      do:
        uses: cloudposse/github-actions-workflows-docker-ecr-eks-helmfile/.github/workflows/main-branch.yml@main
        with:
          organization: "$\{\{ github.event.repository.owner.login \}\}"
          repository: "$\{\{ github.event.repository.name \}\}"
        secrets:
          github-private-actions-pat: "$\{\{ secrets.PUBLIC_REPO_ACCESS_TOKEN \}\}"
          registry: "$\{\{ secrets.ECR_REGISTRY \}\}"
          secret-outputs-passphrase: "$\{\{ secrets.GHA_SECRET_OUTPUT_PASSPHRASE \}\}"
          ecr-region: "$\{\{ secrets.ECR_REGION \}\}"
          ecr-iam-role: "$\{\{ secrets.ECR_IAM_ROLE \}\}"
  ```

on:
  workflow_call:
    inputs:
      organization:
        description: "Repository owner organization (ex. acme for repo acme/example)"
        required: false
        default: ${{ github.event.repository.owner.login }}
        type: string
      repository:
        description: "Repository name (ex. example for repo acme/example)"
        required: false
        default: ${{ github.event.repository.name }}
        type: string
    secrets:
      github-private-actions-pat:
        description: "Github PAT allow to pull private repos"
        required: true

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  stacks:
    uses: cloudposse/github-actions-workflows/.github/workflows/controller-atmos-affected-stacks.yml@main
    with:
      head-ref: HEAD~10

  deploy:
    needs: [ stacks ]
    if: ${{ needs.stacks.outputs.has-affected-stacks == 'true' }}
    strategy:
      matrix: ${{ fromJson(needs.stacks.outputs.stacks) }}
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ${{ inputs.organization }}
          repo: ${{ inputs.repository }}
          github_token: ${{ secrets.github-private-actions-pat }}
          workflow_file_name: stack-${{ matrix.stack_slug }}.yml
          ref: ${{ github.sha }}
          wait_interval: 10
          client_payload: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
