name: |-
  Features branch (Pull request) workflow 
  
  Build, test Docker image, deploy it to EKS `preview` environment depends of PR labels  
  
  ### Usage 
  
  Create in your repo  __`.github/workflows/feature.yaml`__
  
  ```yaml
    name: Feature Branch
    on:
      pull_request:
        branches: [ 'master' ]
        types: [opened, synchronize, reopened, closed, labeled, unlabeled]
    
    permissions:
      pull-requests: write
      deployments: write
      id-token: write
      contents: read
    
    jobs:
      do:
        uses: cloudposse/github-actions-workflows-docker-ecr-eks-helmfile/.github/workflows/feature-branch.yml@main
        with:
          organization: "$\{\{ github.event.repository.owner.login \}\}"
          repository: "$\{\{ github.event.repository.name \}\}"
          open: $\{\{ github.event.pull_request.state == 'open' \}\}
          labels: $\{\{ toJSON(github.event.pull_request.labels.*.name) \}\}
          ref: $\{\{ github.event.pull_request.head.ref  \}\}
        secrets:
          github-private-actions-pat: "$\{\{ secrets.PUBLIC_REPO_ACCESS_TOKEN \}\}"
          registry: "$\{\{ secrets.ECR_REGISTRY \}\}"
          secret-outputs-passphrase: "$\{\{ secrets.GHA_SECRET_OUTPUT_PASSPHRASE \}\}"
          ecr-region: "$\{\{ secrets.ECR_REGION \}\}"
          ecr-iam-role: "$\{\{ secrets.ECR_IAM_ROLE \}\}"
  ```

on:
  workflow_call:
    inputs:
      organization:
        description: "Repository owner organization (ex. acme for repo acme/example)"
        required: false
        default: ${{ github.event.repository.owner.login }}
        type: string
      repository:
        description: "Repository name (ex. example for repo acme/example)"
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      stack:
        description: The stack name.
        required: true
        type: string
      component:
        description: The component name.
        required: true
        type: string
      environment:
        description: Environment.
        required: true
        type: string
    secrets:
      github-private-actions-pat:
        description: "Github PAT allow to pull private repos"
        required: true

permissions:
  pull-requests: write
  deployments: write
  id-token: write
  contents: read

concurrency:
  group: ${{ inputs.stack_slug }}
  cancel-in-progress: false

jobs:
  deploy:
    name: deploy draft ${{ matrix.stack_slug }}
    uses: cloudposse/github-actions-workflows/.github/workflows/cd-atmos-stack-deploy.yml@main
    with:
      #      ref: ${{ github.event.pull_request.head.sha }}
      #      default-branch: ${{ github.event.repository.default_branch }}
      stack: ${{ inputs.stack }}
      component: ${{ inputs.component }}
      #      component_path: ${{ matrix.component_path }}
      environment: ${{ inputs.stack_slug }}
  #   stack_slug: ${{ matrix.stack_slug }}
  #    secrets:
  #      environments_github_token: ${{ secrets.DEPLOYMENTS_GITHUB_TOKEN }}

